apiVersion: v1
kind: Secret
metadata:
    name: db-migrate-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    mysql-hostname: ENC[AES256_GCM,data:rErWOOB0Rhd8rEH5sZmMzUv7uHUJbcB+ro9StGv8yi+CLkSTAYCQyWD+jLjVU1TkkhYn,iv:pJaJOghZy8x7VfILCm2G2byZ88BZbCzGravZ6btiQNk=,tag:tn54AJWfNrJ6JTPMdAy5Zg==,type:str]
    mysql-username: ENC[AES256_GCM,data:mYwI0qvgJg==,iv:hi1/fwIvATT1hzt49hhdMnO+nxZ6F5p1JS6maiTtJFM=,tag:Z+W/FZzjgjt8tAyimMq75A==,type:str]
    mysql-password: ENC[AES256_GCM,data:1WZPqQKYEoub7B7LXeVxw/Xf0P8=,iv:0Pi9XHtLDpywNkQfnTbxIOJLDakauhRezOsGflQR8N0=,tag:hHg0CDvYOVDh4orb5XG0bg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-28T01:53:58Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFnXktX0DuUH3fj5jp6IivXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeHHdPYowRgsRvHVWAgEQgDutQRmqmhAbrev4UmKg70qElQVwIpgPvCxXRHhUBhUDdfM2YGWH4J13V1ZYsOeE+n4lezEDWuN83Hw9lg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-22T03:02:18Z"
    mac: ENC[AES256_GCM,data:2WRruTLYVWMx8wOT5BiENaLqDSqZKo88Cv+bQZsZZqSnab3Ak9UHnywYiR9zZnTq2JQJO1U6uQ34ZYMvps9OmK/8IGQ20foWbJ4IbY/ePOgtX30jBBZ2TOHNjtO5FIp0DTKYqGhLxdxt2PjF+B7cWC51cBR+60vtKXDXnVkfu9Q=,iv:v6RVE/UTYv2Ancv8sUfQmsC08spKnm+so+uKriOMWtg=,tag:2nJkcZ1szK0fCZ3K3gNmrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
