apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

metadata:
  name: kustomization
  namespace: omegaup

commonLabels:
  env: production

resources:
- ../../../base/frontend
- grader-metrics.yaml
- database.yaml

generators:
- grader-metrics-secret-generator.yaml
- frontend-secret-generator.yaml
- omegaup-secret-generator.yaml
- redis-secret-generator.yaml

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  name: nginx-config

patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: frontend-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/hsts: true
    spec:
      rules:
        - host: omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
        - host: k8s.omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
      tls:
      - hosts:
        - k8s.omegaup.com
        secretName: frontend-ingress-compat-cert
- path: frontend-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: frontend-deployment
    version: v1

images:
- name: omegaup/frontend
  newTag: 99f75a5629d13fefdd5a26688a232d29f7fce3d2
- name: omegaup/frontend-sidecar
  newTag: 99f75a5629d13fefdd5a26688a232d29f7fce3d2
- name: omegaup/nginx
  newTag: 99f75a5629d13fefdd5a26688a232d29f7fce3d2
- name: omegaup/php
  newTag: 99f75a5629d13fefdd5a26688a232d29f7fce3d2
