apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

metadata:
  name: kustomization
  namespace: omegaup

commonLabels:
  env: production

resources:
- ../../../base/frontend
- database.yaml

generators:
- cronjobs-secret-generator.yaml
- frontend-secret-generator.yaml
- newrelic-secret-generator.yaml
- omegaup-secret-generator.yaml
- redis-secret-generator.yaml

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  name: nginx-config

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
    spec:
      template:
        spec:
          containers:
          - name: php
            volumeMounts:
            - name: newrelic-secret
              mountPath: /etc/php/8.0/mods-available/newrelic.ini
              subPath: newrelic.ini
          volumes:
          - name: newrelic-secret
            secret:
              secretName: newrelic-secret
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: frontend-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/hsts: true
    spec:
      rules:
        - host: omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
        - host: www.omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
        - host: k8s.omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
      tls:
      - hosts:
        - omegaup.com
        - www.omegaup.com
        secretName: frontend-ingress-cert
      - hosts:
        - k8s.omegaup.com
        secretName: frontend-ingress-compat-cert
- patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: db-migrate
    spec:
      template:
        spec:
          containers:
          - name: db-migrate
            command: [
              '/opt/omegaup/stuff/db-migrate.py',
              '--lower-timeout=aws',
              'migrate',
              '--databases=omegaup',
            ]
            volumeMounts:
            - name: cronjobs-secret
              mountPath: /home/ubuntu/.my.cnf
              subPath: my.cnf
          volumes:
          - name: cronjobs-secret
            secret:
              secretName: cronjobs-secret
- path: frontend-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: frontend-deployment
    version: v1

images:
- name: omegaup/frontend
  newTag: 7b11ab1fbfb2298d7b87ca6f796b3e373f9bd046
- name: omegaup/frontend-sidecar
  newTag: 7b11ab1fbfb2298d7b87ca6f796b3e373f9bd046
- name: omegaup/nginx
  newTag: 7b11ab1fbfb2298d7b87ca6f796b3e373f9bd046
- name: omegaup/php
  newTag: 7b11ab1fbfb2298d7b87ca6f796b3e373f9bd046
