apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    newrelic.ini: ENC[AES256_GCM,data:CEJEMsy8YFZ6qlwtE5qoaHbWduSwCAAneEsgf+dH6Jacz0t6OqansriQ351z1G8vO5Cs+Yq0iEyCwJvFOvpAXupb78AuhVFS+RnoYgzUJcgKqdIacncklJC5ib/rd02nVuZixh+tbDVryTMG7aUBQQKd1BQp+sUyeT5DQ4NMBYrNBjKpIC7XLYWHPZone2Vk8j85snb2KL1lfh6dm0YdPeslxzjKAt3r786k2lrFxuX9q4HIWpYgzBevQhqv84PwwQrje7eTHzLzC9KOgCiatIl57zmbfxY6WO9HAyXee0Pr5wt2AanMre/aPHoJFMzTikEMSDCWr/PiyDEY09rae2wrTeFZDiwJ9Ikjhytyiui3NeSNqMz9IHnlOQkp1HX1oo7Q2bpn4Ph1cJNNHx5Jbk6Q6ZhXQzUgdRzoqzVl7GkYTR0xtT8cyRM5rWQYzUBW7uOnA/Qq0xhl33z8tFZ5BLYQ346ZPwXodsvc7RTCfxFJjkkLaKZPyw4xcNuE9wHhYQ/KrAjUJ+oyPLPZtsdjIgJqaMFo,iv:iTsTB0rbe9OmTy0iYE+RRn3rkq+VqPc7BWNwSqkpHFM=,tag:eN6mnCQid1Osvq5afVl+sA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-11-27T13:45:49Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFXxnfFaChIpJot/lj045WaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzUcAOHaVHBlYzZ+ZAgEQgDt6HwS1MSmJJeSicuyc/NJkMtVyAgAEe/QU+YJVPaLmxhzMqEXlkLo/C2ns/jeJ9ki7GeHHpmJq8udIpw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-27T14:17:10Z"
    mac: ENC[AES256_GCM,data:4sG+7YKJKne+MBj8wOzP6rvfN4bq+MOo/TOA+y4/IIjpgFpBVaNcbxerM2rSbPYsWj/ktQeMIqQ+GZLbwPKur+ANeCByEY+T5TqwhVBUVJorSNluDxpBm1oN0k2SJEFGzJjcwn9Kuak2f5GPmAlOrevgOsmaDmW+FSvE2QU1ldQ=,iv:EPjOHL0nlhRoE3f7GN5eJHKQUlXXry4A5uwFFaLr0qg=,tag:ZLODuS4+I+rH14/C6Nz/Aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
