apiVersion: v1
kind: Service

metadata:
  name: grader-runner-service
  labels:
    app.kubernetes.io/name: grader-runner
    app.kubernetes.io/part-of: backend
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grader
  ports:
  - name: grader-runner
    protocol: TCP
    port: 11302
    targetPort: 11302

