apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: omegaup-problems-pvc
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: omegaup-problems-csi-pv
