apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: omegaup-backend-pvc
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: omegaup-backend-pv
