apiVersion: v1
kind: Secret
metadata:
    name: gitserver-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:H5tOxANVZVRQSWfNg2FTrIBkJj3WRhXNJ+OxJVRV8+Zz4/En9RHpf4mBpzwA12zR5BSwbDTeR/osy3dHCxyvCKzZRKXC267ZaaHMAqAOQ8YQNaw1sI09tu+9UISI3+3moTRWV6Ko2Z5Aap7/hpxPebbxuzJ7ziKvClE613pJGnCnIbdsHaQCZNuvo9FjQ6x9BU/XeE/owc4gHCUkZhcSfUbMXVeBk48ojsl4xSxp8iHf+cGfaO6NdWZ0TPT3jfJYYQ12NoT7Uq7n3Pu5PutrpMkbMMQ4rkVZtLaQitHfK5yoMdJA49KUwE5SD8mWDt/e/xCAhPRt6mOd8jKHUR68Pf2TT4FnLkRKCLnzregQoN6/34l8RhqrHqNAxB4vCWz1GgzF2SEfRAeA08yc1d8CbCJYavnnnIC2Jc3+SapOYbk/RQpzlzYgfqKUh1MrW2VB6Bj6NJpqwX+Ss1GwoHWFU9Xyi6ZuLEF+GmRmnyvj3uAsxgV/wu+rIsnEGotm5JkFPdjAygxuz6eUC6qy1Ft+C1Y9Ef/8cobHjtMnLVAhLqHuW6NRRsmuk3xVmTJh3sK5WzJtFoXmRoFKU9ROO3qIahu3QW0emJHHMrHZj3KluY5M5yzpNBLdHkOpc7zD64GVi+4RV2EQEJsyhUFBXeQ0nWjAOVr19fWR8sXznQt2AMTHXjQ0oDXxnjxBhju5SfTHfut+rx3S/n4ynqi7yc6k0l297ptqcuZDZhK+BsEi,iv:e8fu3YHoRLVqlN1UM7NHeJ9w+0uF7S+b3t/laROoKjg=,tag:hA0tWt/lRFsDAanEF2wzRA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-28T01:53:58Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFnXktX0DuUH3fj5jp6IivXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeHHdPYowRgsRvHVWAgEQgDutQRmqmhAbrev4UmKg70qElQVwIpgPvCxXRHhUBhUDdfM2YGWH4J13V1ZYsOeE+n4lezEDWuN83Hw9lg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-12T13:55:31Z"
    mac: ENC[AES256_GCM,data:4Y5TGabn6vhUkE+eFuLmdxBVu5jLXVcYwq5StArROjEQ50NCIoIECc7EAP6etUyNh3XDBAQGTa0LiWstGf3C+9gaComu5zCBT1FntBOQMA4t0gtnk7nrz8YmQ4IZXlDHpoUhMNG2tLnz1QDtyqK6SZ3lwSc2e9TVV5wq1JRBnQk=,iv:rPCxRk9IQVuUtH92JvjBaYRuRDZ/A9re0P6GxPi9lnc=,tag:LdECWkivRVkvdUiKeJXtDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
