apiVersion: v1
kind: Secret
metadata:
    name: gitserver-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:MV1Hyx8JoAih7K5R49HiSlo5A0bKF8ddmI2ojOwROoavnwfGiU4FBkRBCvbaaJ2DTdYJj6Jp9ubdFEfTSQcpkMkF4uAFhv0Xpyjg+gt5hR9OvoOTXJ6Aoh/dSs5IuKALgwqlJUc3p5PPqUbI2g5ZJQRLLScxXYzMVrPuIK2Oaul89iA9jz1G/WdSsMAHAtpMtBAn2djaF07LSI9MSi0KMdNZo8Sz/Q/nbL4kl0bLGZZdCzFmJVJwl3fvxqkBWCs3RGxAkekcX1Xg9XGiO7mmoxaOlTFZgyTzTYmdK7FC/EUrNcRmkyA4AqpKpa9r7tYeMSLgmJsxXe2HUkvc8EEqBbYgG5O8lPrxQ7hN5YwS7Nb8vLRu8h+NUnsol4dZO132rec+wPJZaZ9Ksjh7sK6hMG+feqJQH2PYJQmwGLVTas+E0tEZVxA1xj/WUM38tONDJCgtj1fZeHPlmos0dXeEUQur6dN6bG/fBfvbnuS0Tgnpz1RjzyR3TSmayt4CLON+3UxQJcY/iMOYIDrllrKRV0AFucV5Tc5X3k+yfgTXX4e9yHGqxjj4aKyFJqauaX7Xcv0R+BSdljm9PwbsL3pPiVrP2CcKPveMHo0FPpvTgYwdQXrcaqeFzoTZsERJem8TNhG299LaHf7pd0dtpuSE9pwGNbozsRtrjAKqqAzlYc9rw0/i8SvWfE/IpTIBkeUpvpNTOWYCJH8O0c5tNNtArqq5+eKZZ+V+kA==,iv:hYYrUdPLCAtpjvn8cVOqE80z5CKTweswXollabdQs5M=,tag:8Gg7mM1dZjTYggVKusyqcQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-28T01:53:58Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFnXktX0DuUH3fj5jp6IivXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeHHdPYowRgsRvHVWAgEQgDutQRmqmhAbrev4UmKg70qElQVwIpgPvCxXRHhUBhUDdfM2YGWH4J13V1ZYsOeE+n4lezEDWuN83Hw9lg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-05T03:52:43Z"
    mac: ENC[AES256_GCM,data:U6oTV5p30cwPpuA0EFzDxAC8Rw0mL+esnuF/di7wYMN4Sebwy5MQBPi5bkkjHBr+mA6z+YeOpAMekrGSENN7WJ7Hv7MOGxkpwnlgA+Ey7Uq0kFYynmjVBnpWyiv7+aSgsjXgseaGjKxlseqz9r+jnJ6xTSCYIwMJBuqtoj/osxg=,iv:/tNSOORvsQRTQ3u1lojVTi78tTyQBCXtQlMfADKmufs=,tag:nEaaPpFoVUXriDmTLxP89w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
