apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

resources:
- ../../../base/backend
- deployment.yaml

generators:
- grader-secret-generator.yaml
- broadcaster-secret-generator.yaml
- gitserver-secret-generator.yaml
