apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

resources:
- ../../../base/backend

patches:
- patch: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: omegaup-backend-pvc
    spec:
      resources:
        requests:
          storage: 100Gi
      accessModes:
      - ReadWriteOnce
      storageClassName: gp2-retain
      volumeMode: Filesystem
      volumeName: pvc-2131c99a-5c2a-472f-aee8-5835b0506fc4

generators:
- grader-secret-generator.yaml
- broadcaster-secret-generator.yaml
- gitserver-secret-generator.yaml
