apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

resources:
- ../../../base/backend
- deployment.yaml

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grader-deployment
    spec:
      template:
        spec:
          containers:
          - name: grader
            volumeMounts:
            - name: omegaup-problems
              mountPath: /var/lib/omegaup/problems.git
              subPath: problems.git
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gitserver-deployment
    spec:
      template:
        spec:
          containers:
          - name: gitserver
            volumeMounts:
            - name: omegaup-problems
              mountPath: /var/lib/omegaup/problems.git
              subPath: problems.git

generators:
- grader-secret-generator.yaml
- broadcaster-secret-generator.yaml
- gitserver-secret-generator.yaml
