apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

resources:
- ../../../base/backend
- deployment.yaml

patches:
- patch: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: omegaup-backend-pvc
    spec:
      resources:
        requests:
          storage: 100Gi
      accessModes:
      - ReadWriteOnce
      storageClassName: gp2-retain
      volumeMode: Filesystem
      volumeName: omegaup-backend-pv

generators:
- grader-secret-generator.yaml
- broadcaster-secret-generator.yaml
- gitserver-secret-generator.yaml
