apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

resources:
- deployment.yaml

secretGenerator:
- files:
  - broadcaster-secret/config.json
  - broadcaster-secret/certificate.pem
  - broadcaster-secret/key.pem
  name: broadcaster-secret
- files:
  - grader-secret/config.json
  - grader-secret/certificate.pem
  - grader-secret/key.pem
  name: grader-secret
- files:
  - gitserver-secret/config.json
  name: gitserver-secret
