apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

commonLabels:
  env: production

bases:
- ../../base

configMapGenerator:
- behavior: merge
  name: fluent-bit-config
  files:
  - fluent-bit-config/output.conf
