apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonLabels:
  env: development

bases:
- ../../base

resources:
- ingress.yaml

patchesStrategicMerge:
- argocd-server-deployment_patch.yaml
