apiVersion: v1
kind: Secret
metadata:
    name: grader-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:CpdBTOs142nvDJ2VABN7yCpmDmuW3lLRtD+bMfkrfJZw3GODgLgodsrOTes4m1+zkkWJF20Vd0OphYBmPLJICLsgAW3iU/eim8A3cbcH7J+NaOMuf+mL+3SfdjUypiHpn2paCTFEudE0+X0mpwE5mNL1iXCr8s5MDmQeAjTNVaPAfz8bQXiSbwsIbiz1zt75oXrNRjojABiPVkfyZ0i99piBUHS5uB7tJ6txYwAVzI+BNvfsP5DovkPrcLDhBPhMYauNLRQpeiyPZ3ooY8qAhd7EU757/vff2mfir7qQ2frImcCKBTqlWamjWv9Dk3UZsZfNBNaZmGyS73H4cQsjS78YecnhtVXMSYRDkCoE1q2BOJIhvYO+to7GPwDX3B3FTqed05mmt1BqzrmreSWBN2dIhaP64Yqh6MsnCOn0BT4eHn8YqYAOC15Igcia8Zn5yFGOk/S1flA+vHP2Xh/nWtKAL5Ez1bFF12rnf1dtmBwEqtIT1uvouOhvZ55nrqYv7pAABeC0NiVLEXfToBDYhSMuOizfEutVJ/vGsuRSnxt52R3pq0nSZ+0b0TGmgUIYsi03jyAWcU45/pw2rUJ5hPUi+tMn84nUOSIpcnTETx5b1Y6xonJnGxF6ULrjV8UdeZJq7mpUgdSc7xbdcj+rPdPe2HKgT/DK64yazm5PFTZGOHRZ1wUM3yWSDVJTP3tkCXcK+MhhGwe8bT7s2076LwdRFUOr7G49GmgM8/L97N2RzyU0UjcpAoRghXau0aGWDMCnfgtkbYw5s+WpgWQM9G4Lqdw6av6GZ7nMOBH6j9draUrfdyCppqVERHHPKtbZCRg0ZZoI,iv:3nPzocQ68z2W1KagDWbIFxFzt7qZ7bcaHlvrWRXPvP4=,tag:HGCsi2Ag+R3BljTsK4Tflw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-12-14T15:15:29Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQGZPCMDoXwJuSkL7De8otw1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfBaIg+xh6GTL20kFAgEQgDt6WC8w/c3a1e1CBSfGwql6fUNtyI5qCi8CZRO7oU2x7/PzH5N62dD8cLpoK36lkUfbUv4iLVbqszBDKw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-31T16:49:26Z"
    mac: ENC[AES256_GCM,data:ysEhCniVIXMomtgVdbTSiDBH8QN6AM0sWY2gWPa3faJyWvV1T7KovrtjD5gOhX3j8IBg7Y/ZROYHR5u6c8c/fBlgBh7Qn4ooLY0ry/cdA85pnfJp2omXEnspi2rXGDNErD0s4XjXzEtK5qqrkcl0ImQPw9Qe0PJgaFBr3++roi0=,iv:Sw7PpBYQMo7FlwsfwI1Dt4OJKg0C3uffeFjhFd8qvZg=,tag:VEkC3N+xX4vVjT8b93KDrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
