apiVersion: v1
kind: Secret
metadata:
    name: grader-metrics-secret
type: Opaque
stringData:
    CONNECTION_STRING: ENC[AES256_GCM,data:cmvPar3WhC0EZ9pX8CywEcGcIiHSJeJ0Kdv4kTg33W2XYTAJ5BQwZLgfDMCAnvlcwskf9BT2zHSfUapyrUxJIpuzrgRAHJxUC4EY5npY/8jM7qh7USeT+356nk1g7LcumvAvaZTf9TzfrgA7+orGf3R7SHfRMSLJmUx7gKk=,iv:c7HSCIXudJ4CkMkUrtDn3cDVB7p+3rPnz3i95kzfOwI=,tag:ezLA2FRS/1rtdxf7dJ+8tA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-24T17:21:59Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQHAta/LFaz5LkmqJCzisGAnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDRUqNobePHEr+fXEAgEQgDtu7BKOOECn2MlX43LRtSsv+U8ZmWHbO6d8AgD6FRPijwNXVMcZkU1JQJhTq/tmAW9kOiSiNmvAjOiJIQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-24T21:40:31Z"
    mac: ENC[AES256_GCM,data:jIequh/wepx/t7rwr9cu+pQvi5c94ls78Sv2q8/5INFcpLYYUSFK3fNbjLbPXY1OjYxvvvn3DcSFu4CorC5JVUJCbH2wOt9l7sM/OylixiZiL+AWaimP01J0vREcDGs3IKTfa7K3pX3P9aVljO7qsxDcMDu3RJbXirtVxGlzWBo=,iv:pAlFkcOl7V9pi774JkgoVTC4KdyrZ3ov43k5AmV7jYg=,tag:bmUrYnBpyKy/aYF6I82tjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
