apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

metadata:
  name: kustomization
  namespace: omegaup

commonLabels:
  env: production

resources:
- grader-metrics.yaml

generators:
- grader-metrics-secret-generator.yaml
