apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    redis.conf: ENC[AES256_GCM,data:6NjkPd0G6NNOv1ndal0si2SQCO38ONAG7hp0Gva21al61PrAgCu9sm3An3QkY/rtFpFEwWqNF2fAXKLvIX6JLQIjwyLJZRtRTO8mrvJdbJxDePKhFBSt87Lw,iv:trA1yE25doQXvLhDiMB+udzbdQISZAg7+9q+62Uqc+g=,tag:8btMCDe+L3DNZmBF+g4Q/Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-28T01:53:58Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFnXktX0DuUH3fj5jp6IivXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeHHdPYowRgsRvHVWAgEQgDutQRmqmhAbrev4UmKg70qElQVwIpgPvCxXRHhUBhUDdfM2YGWH4J13V1ZYsOeE+n4lezEDWuN83Hw9lg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-04T02:35:42Z"
    mac: ENC[AES256_GCM,data:U00k1ZLPKiY/ZRj1wy/PjSjGWXACVKeKoypju4a4MTnVL7tTZqjgzbO3QxwGs0/N2vwLBUk51gavDKSW1PTZRxB5lSEu8poT9ADgdrqIw/UnnrF5kitM3OMKcAmPfycTOUpWLSE8sWOQ6KESXTTEd0AJwekrhR3x2SUZgxYS+S4=,iv:MnK8Y+Q+t8y1kpOvHsot1gmKeKUOXm8pBpiBx2JTYQM=,tag:FMYmfBcrG+yco1ldQz9tdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
