apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup-development

metadata:
  name: kustomization
  namespace: omegaup-development

commonLabels:
  env: development

secretGenerator:
- files:
  - omegaup-secret/config.php
  name: omegaup-secret
- files:
  - frontend-secret/certificate.pem
  - frontend-secret/key.pem
  name: frontend-secret
- files:
  - broadcaster-secret/config.json
  - broadcaster-secret/certificate.pem
  - broadcaster-secret/key.pem
  name: broadcaster-secret
- files:
  - grader-secret/config.json
  - grader-secret/certificate.pem
  - grader-secret/key.pem
  name: grader-secret
- files:
  - runner-secret/config.json
  - runner-secret/certificate.pem
  - runner-secret/key.pem
  name: runner-secret
- files:
  - gitserver-secret/config.json
  name: gitserver-secret

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  name: nginx-config

resources:
- ../../base
- database.yaml
- backend.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
    spec:
      replicas: 1
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: omegaup.test
  target:
    group: networking.k8s.io
    kind: Ingress
    name: frontend-ingress
    version: v1

images:
- name: omegaup/frontend
  newTag: latest-main
- name: omegaup/frontend-sidecar
  newTag: latest-main
- name: omegaup/nginx
  newTag: latest-main
- name: omegaup/php
  newTag: latest-main
