apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    dex.github.clientSecret: ENC[AES256_GCM,data:fYYrE3s9tsht0ZT2ui0l/SK2VGevjQRUlanwcbTYgS+dpJJa+l2PEg==,iv:0mPbOlNcjC4qODwo7dnNZwSZY2CNMycqowBQdKAwHnU=,tag:yrbIDPyVsK94QiwqswC89g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-24T17:00:48Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFKdzrvzW9Qb1XKKWb0uJ7lAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyk+e2HnvYmRctgTRAgEQgDuWvhO1uNcg5ZgzU9Z1K9+8g6XrbF3e0zKiUFswFEaj4GkQQ18qYPCh9uwNw5MbwXQ031H0Awv/d2hJuQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-24T19:09:22Z"
    mac: ENC[AES256_GCM,data:kGNCVOHPGvOEif3a+ItTzX8hwebGVxoNLSxsBAfK6oSOyPT/AtDDNLej8xWEspVuwbdd/NuyiH87jQuXpa5RU8Pw3XTQ+b10TjvG1ihlvJWryIQwfVT9100GepyqCin7PPniQh+VrKXZYSq1NxpCMEAKe76Gv826VCLnle3/jiY=,iv:kfVx9S6rl7bUDzyJC8EaZ3YM51BeomRy/Mp4cxsR92s=,tag:Ld5VtXw9Zfo/Y4/tMiQePw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
