apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    dex.github.clientSecret: ENC[AES256_GCM,data:fYYrE3s9tsht0ZT2ui0l/SK2VGevjQRUlanwcbTYgS+dpJJa+l2PEg==,iv:0mPbOlNcjC4qODwo7dnNZwSZY2CNMycqowBQdKAwHnU=,tag:yrbIDPyVsK94QiwqswC89g==,type:str]
    webhook.github.secret: ENC[AES256_GCM,data:pV8uLb2ygllT3djmAdkpWcViovxR5PFDOiP1AG4Plnc=,iv:/hMgNZK1tdCKujshSc5lFE/to/IG6OgXZQpxf2seGtk=,tag:vE41bDAN7iKia2uQKTEsTQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-24T17:00:48Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFKdzrvzW9Qb1XKKWb0uJ7lAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyk+e2HnvYmRctgTRAgEQgDuWvhO1uNcg5ZgzU9Z1K9+8g6XrbF3e0zKiUFswFEaj4GkQQ18qYPCh9uwNw5MbwXQ031H0Awv/d2hJuQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-24T19:18:45Z"
    mac: ENC[AES256_GCM,data:Jd/lyX6OvnoOv9EKtRKI5Kvl0iZcNv96DGl7IoPGSqjv3WLLfkkbJaTooFaVUiIw1GBq758QGcjWUPxhMx2mayDgq8H8XATpVhp9YneHUah5eVsee/KfHMSvANYbOdLCC0+6apTHIxuI0E39ww0oO0xcNPszcWFmsJ6LmfTb5DA=,iv:9ub3RySF1FyUyYjXSZMvaysTTkmMvJPPSj+gNFJjCgI=,tag:HHmJGPXdC6VxgS5cL4jY4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
