apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omegaup-problems-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omegaup-backend-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  labels:
    app: backend
    env: sandbox
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
        env: sandbox
      annotations:
        prometheus.io/port: '6060'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: gitserver
        image: omegaup/gitserver:v1.8.2
        command: ['/usr/bin/omegaup-gitserver']
        ports:
        - name: gitserver
          containerPort: 33861
        - name: pprof
          containerPort: 33682
        - name: prometheus
          containerPort: 6060
        volumeMounts:
        - name: gitserver-secret
          mountPath: /etc/omegaup/gitserver
        - name: omegaup-backend
          mountPath: /var/lib/omegaup
        - name: omegaup-problems
          mountPath: /var/lib/omegaup/problems.git
      - name: broadcaster
        image: omegaup/backend:v1.6.3
        command: ['/usr/bin/omegaup-broadcaster']
        ports:
        - name: broadcaster
          containerPort: 32672
        - name: events
          containerPort: 22291
        - name: prometheus
          containerPort: 6060
        volumeMounts:
        - name: broadcaster-secret
          mountPath: /etc/omegaup/broadcaster
        - name: omegaup-backend
          mountPath: /var/lib/omegaup
        - name: omegaup-problems
          mountPath: /var/lib/omegaup/problems.git
      - name: grader
        image: omegaup/backend:v1.6.3
        command: ['/usr/bin/omegaup-grader']
        ports:
        - name: grader
          containerPort: 21680
        - name: grader-runner
          containerPort: 11302
        - name: ephemeral
          containerPort: 36663
        - name: prometheus
          containerPort: 6060
        volumeMounts:
        - name: grader-secret
          mountPath: /etc/omegaup/grader
        - name: omegaup-backend
          mountPath: /var/lib/omegaup
      - name: runner
        image: omegaup/runner:v1.7.0
        command: ['/usr/bin/omegaup-runner', '-noop-sandbox']
        ports:
        - name: prometheus
          containerPort: 6060
        volumeMounts:
        - name: runner-secret
          mountPath: /etc/omegaup/runner
        - name: omegaup-runner
          mountPath: /var/lib/omegaup
      volumes:
      - name: omegaup-backend
        persistentVolumeClaim:
          claimName: omegaup-backend-pvc
      - name: omegaup-runner
        emptyDir: {}
      - name: omegaup-problems
        persistentVolumeClaim:
          claimName: omegaup-problems-pvc
      - name: broadcaster-secret
        secret:
          secretName: broadcaster-secret
      - name: grader-secret
        secret:
          secretName: grader-secret
      - name: runner-secret
        secret:
          secretName: runner-secret
      - name: gitserver-secret
        secret:
          secretName: gitserver-secret
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service

metadata:
  name: backend-service
  labels:
    app: backend
  annotations:
    prometheus.io/port: '6060'
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: backend
  ports:
  - name: gitserver
    protocol: TCP
    port: 33861
    targetPort: 33861
  - name: grader
    protocol: TCP
    port: 21680
    targetPort: 21680
  - name: grader-runner
    protocol: TCP
    port: 11302
    targetPort: 11302
  - name: ephemeral
    protocol: TCP
    port: 36663
    targetPort: 36663
  - name: broadcaster
    port: 32672
    targetPort: 32672
  - name: events
    port: 22291
    targetPort: 22291
