apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup-sandbox

metadata:
  name: kustomization
  namespace: omegaup-sandbox

secretGenerator:
- files:
  - omegaup-secret/config.php
  name: omegaup-secret
- files:
  - frontend-secret/certificate.pem
  - frontend-secret/key.pem
  name: frontend-secret
- files:
  - broadcaster-secret/config.json
  - broadcaster-secret/certificate.pem
  - broadcaster-secret/key.pem
  name: broadcaster-secret
- files:
  - grader-secret/config.json
  - grader-secret/certificate.pem
  - grader-secret/key.pem
  name: grader-secret
- files:
  - runner-secret/config.json
  - runner-secret/certificate.pem
  - runner-secret/key.pem
  name: runner-secret
- files:
  - gitserver-secret/config.json
  name: gitserver-secret

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/php-upstream.conf
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  name: nginx-config

resources:
- ../../base
- database.yaml
- backend.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
      labels:
        app: frontend
    spec:
      replicas: 1
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: sandbox-k8s.omegaup.com
  target:
    group: networking.k8s.io
    kind: Ingress
    name: frontend-ingress
    version: v1
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: frontend-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/hsts: true
    spec:
      tls:
      - hosts:
        - sandbox-k8s.omegaup.com
        secretName: frontend-ingress-cert
- path: db-migrate-name.yaml
  target:
    group: batch
    kind: Job
    name: db-migrate
    version: v1

images:
- name: omegaup/frontend
  newTag: 432a690b717a53f8d03bc834b0916cecba9d3062
- name: omegaup/frontend-sidecar
  newTag: 432a690b717a53f8d03bc834b0916cecba9d3062
- name: omegaup/nginx
  newTag: 432a690b717a53f8d03bc834b0916cecba9d3062
- name: omegaup/php
  newTag: 432a690b717a53f8d03bc834b0916cecba9d3062
