apiVersion: v1
kind: Secret
metadata:
    name: omegaup-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    config.php: ENC[AES256_GCM,data:6zu9oc6eBO6DmSNg7P4R6jwNz/RURgpYBNCu3+VXJsssY14J/o3uHXhIauYn+Xlkoxq0ZIDHo2u8ald09TbUMt4Wa63Q9op+f2xyytBlta129qBb6sSG5qOx+BaFdYYwyyDZlmlokS1f15GNpmiK0HIRIxDCocPX33BYRzzrCv3Wr/P4L3AORDs3/UEDf51fhQklZb4UCk3EvFREmuGPu8B5CmToHGajtm0+fLqAygH+alyczScggKVFeLXJp9e4VnEI+l6u9KSOAEMaS66dYYqWECRk2uhcPxIl7Jq2bQCQnFMMOq7rWrvGQy2ReyJ5vJNG/JhIH52QrmLvNaU9DWA4jemmdT6LkeTl0JGD3Wyvbh7R6J/UhB8AV3rqlumHD+D/CFPIXGxIHJjEfKV/uOE9S9u/xnoB1nRPtxlhFDmIvzMCEoimb7kzL4nF/xSD2sPrWMpl0k6/IYPhddf10nbcNHCks+eEMKiQ1qmxQBP4KkOpuh629UVFJtej/OhwCAtQ6uyZnCGGYOa2YPTxmsxyDw2N2dDOCDHUEFgG2qydC9duqMvr2yUbN7+abicflJDtOdjPYk8IKby7PfFfN0M9g/18VzOF3Pml2k8f7xX4aqRR4wGIdXIlbDRsxFhcQHgrt3l8rd2DJSnhnsvDWiG0AiInYdYdK79rMLSPTsit71oiFXsffi7oQeI6Uxik/i+Ur59rQUv94IZnCoU0e3P4qwzLzam1YoGBvzbNbvtfZb06vLqrkpCtcLPyAPxhdnvZxNODhiHy4EjNg4HcoutDmpkcWi0eypfuB0ZMOjqBKv/1J2Lg93frEYB7BcTHOB0+f71rB2olndnNMxm0tTI3iU57kQzEP3aN9KHHQ4eTmEMrE0NkSNHnL3WNt3spWmbnG9dYIoEzTYNi+/PfP4VkdNpoFjbwVj9CqcoJMCxq1KFCXN2UU3Cy9vvl2seEqJ4nYtlxzJJXJ1DgpY8FYHZbJHV4W5ISRYgF2peDOdvtmKDqCPXIVaAsmWCzAuHOoo/h5zqYSfv6wdlOMS38Ouaqp9Pdq4VqdcaEk4Izqx8qrxGTjGJpoqVRwjUKA5SDz91b348dWhb7fTzrEQ6f0n1eglvIOsVxqNQ9sv+IqaMxbqxrhay6yvC4z/vnLhlUrUNavjc4NuN8EMK+d7jHMxf/AO5N7GMtvxJ15CZqGgAf9VwO6mhS1XvWwkS+AB0gaTL62SWtxCruGeThO52x2Sob9ZQZbExkoJ1HtAjS9ywubkde2w==,iv:4LKC1doT5SVh1p7tKF9ZrBtdUkGcHtf9BJSR8g5Y4/o=,tag:7tt+XINgUVTss6bCr+haxg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-10-28T01:56:52Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQHiRQu9vw0oibo8boKi9yNBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbWOBF9HzZzWjNlxxAgEQgDsrijaC0j7ScZPyY0/iMVVo8BIDDAW7gXqekC6D/6pLQB6O2trMMz7PoelUmRpiPILAFBAqbehcTRmzQA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-04T02:30:40Z"
    mac: ENC[AES256_GCM,data:O3Tiz00EE82iTUlm4dLxqPhN8FxKNfnZ+taGNtDB+GkVYokoc2cawhGfYNE6ptfosafPc5Bf020lLmLhY+IypGvj73pT2IU30toof0qLvdN8F1UvoTM1oxsE0Rx53aXxlAaeM2ItR9mWJy4EeTV9aKE9sbCypzUobPP3SPmWvaw=,iv:dejjsNZVMbNDXEZdCUi1GALNizEek6fAPJMjy6UNWVs=,tag:526P6gtAGqsyhQXqw88Bkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
