apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-ingress-compat-cert
spec:
  dnsNames:
  - sandbox.omegaup.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: frontend-ingress-compat-cert
  usages:
  - digital signature
  - key encipherment
