apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup-sandbox

metadata:
  name: kustomization
  namespace: omegaup-sandbox

commonLabels:
  env: sandbox

generators:
- omegaup-secret-generator.yaml
- newrelic-secret-generator.yaml

secretGenerator:
- files:
  - frontend-secret/certificate.pem
  - frontend-secret/key.pem
  name: frontend-secret
- files:
  - redis-secret/redis.conf
  name: redis-secret

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  name: nginx-config
- behavior: merge
  files:
  - fluent-bit-config/fluent-bit.conf
  name: fluent-bit-config

resources:
- ../../../base/frontend
- database.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: php
            volumeMounts:
            - name: newrelic-secret
              mountPath: /etc/php/8.0/mods-available/newrelic.ini
              subPath: newrelic.ini
          volumes:
          - name: newrelic-secret
            secret:
              secretName: newrelic-secret
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: frontend-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/hsts: true
    spec:
      rules:
        - host: sandbox.omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
        - host: sandbox-k8s.omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
      tls:
      - hosts:
        - sandbox.omegaup.com
        secretName: frontend-ingress-cert
      - hosts:
        - sandbox-k8s.omegaup.com
        secretName: frontend-ingress-compat-cert
- path: frontend-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: frontend-deployment
    version: v1

images:
- name: omegaup/frontend
  newTag: 7f2e8b959c791040c768d2e87f8a67f2925bd0ca
- name: omegaup/frontend-sidecar
  newTag: 7f2e8b959c791040c768d2e87f8a67f2925bd0ca
- name: omegaup/nginx
  newTag: 7f2e8b959c791040c768d2e87f8a67f2925bd0ca
- name: omegaup/php
  newTag: 7f2e8b959c791040c768d2e87f8a67f2925bd0ca
