apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup-sandbox

metadata:
  name: kustomization
  namespace: omegaup-sandbox

commonLabels:
  env: sandbox

generators:
- omegaup-secret-generator.yaml

secretGenerator:
- files:
  - frontend-secret/certificate.pem
  - frontend-secret/key.pem
  name: frontend-secret
- files:
  - redis-secret/redis.conf
  name: redis-secret

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  name: nginx-config

resources:
- ../../../base/frontend
- database.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
    spec:
      replicas: 1
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: sandbox-k8s.omegaup.com
  target:
    group: networking.k8s.io
    kind: Ingress
    name: frontend-ingress
    version: v1
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: frontend-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/hsts: true
    spec:
      tls:
      - hosts:
        - sandbox.omegaup.com
        secretName: frontend-ingress-compat-cert
      - hosts:
        - sandbox-k8s.omegaup.com
        secretName: frontend-ingress-cert
- path: frontend-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: frontend-deployment
    version: v1

images:
- name: omegaup/frontend
  newTag: 646eeaf76200d96604f5af6c180e704290757e41
- name: omegaup/frontend-sidecar
  newTag: 646eeaf76200d96604f5af6c180e704290757e41
- name: omegaup/nginx
  newTag: 646eeaf76200d96604f5af6c180e704290757e41
- name: omegaup/php
  newTag: 646eeaf76200d96604f5af6c180e704290757e41
