apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup-sandbox

metadata:
  name: kustomization
  namespace: omegaup-sandbox

commonLabels:
  env: sandbox

generators:
- omegaup-secret-generator.yaml

secretGenerator:
- files:
  - frontend-secret/certificate.pem
  - frontend-secret/key.pem
  name: frontend-secret
- files:
  - redis-secret/redis.conf
  name: redis-secret

configMapGenerator:
- behavior: merge
  files:
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf
  name: nginx-config

resources:
- ../../../base/frontend
- database.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
    spec:
      replicas: 1
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: frontend-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/hsts: true
    spec:
      rules:
        - host: sandbox.omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
        - host: sandbox-k8s.omegaup.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 8000
      tls:
      - hosts:
        - sandbox.omegaup.com
        secretName: frontend-ingress-cert
      - hosts:
        - sandbox-k8s.omegaup.com
        secretName: frontend-ingress-compat-cert
- path: frontend-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: frontend-deployment
    version: v1

images:
- name: omegaup/frontend
  newTag: 25cba1612f3788fe3d91b8aa03c93ed639ce8345
- name: omegaup/frontend-sidecar
  newTag: 25cba1612f3788fe3d91b8aa03c93ed639ce8345
- name: omegaup/nginx
  newTag: 25cba1612f3788fe3d91b8aa03c93ed639ce8345
- name: omegaup/php
  newTag: 25cba1612f3788fe3d91b8aa03c93ed639ce8345
