apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    newrelic.ini: ENC[AES256_GCM,data:+FXOG/pksr0qLczoifGKHEvGne0ViycnlNDJ3AnX9rVisRTJMqgMGNVC3JX3DGyb9bPiS64L/TfF2hD2AbsfMaIbEAyasjr+U3Y1fsH30xdZpm4Jfb4qGeePxENLVocXt13iXVJ1St0Dqu3vZ38Sd7cE0Sgqlh/g7Gldz3Ddz3KsHsQaVSAKleQeqI9hTVpxaJdJ5KYy2AR1MagwVD7Uv3hdTCni9R78LFpXi0sMOlGkAhNG3TKSoMmhSaCYU2OgZ8/yV9KxbecGcf36KXNYN7csBw0XTFrYiveyJ1ilcfLoKnbPNkSPWYQvxOKZShcRbUf7C3tbUZqUxr36BqFAH8tqnQIb4Aye/vM/aHpchqV+9rlM3cvtmpZOIoj4OvWvSH1pFXecH38geuPJ8r+Xnp0aEhYc3/7Lznp28JMG0Sxsa1O5tDaNKklxg0+NqMpXJZGflSCQblmpHA+kD886ktrRQaL1tEnXs50hpfzVZNo4JMOVX158DX7xiv2opGB6LtWreYoP9fLD4PuczWT/WKk5fJv1vpF2Z+ewKOA=,iv:f3DrUhEJQAZ284ef93p5fF/cbgL+4l770oK76yEbrBU=,tag:+mQJ6+Dsrue5jz80+84Xnw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:273107833591:key/mrk-b51dea56f02f4964835066e80ee531b0
          created_at: "2021-11-27T13:45:49Z"
          enc: AQICAHik82tDrWUjAnFKor0DW0Qtxt+MUW7jXDsQO0uycf6klQFXxnfFaChIpJot/lj045WaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzUcAOHaVHBlYzZ+ZAgEQgDt6HwS1MSmJJeSicuyc/NJkMtVyAgAEe/QU+YJVPaLmxhzMqEXlkLo/C2ns/jeJ9ki7GeHHpmJq8udIpw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-27T14:00:08Z"
    mac: ENC[AES256_GCM,data:5NIvvrYtfqz75wnncTYtn3ytcVQVd3+fiWgfSezPDqh3qLVt34Q0h5BX6oDD5khYI0AHr0tim/zQtkYsI1mtNBgauC4gzpvvp/5IL9dHFrfkWkBSxULRbrEKQ8pUaUgXuOtOBINAlYJH1oSd9T8XlDLeqyVq15NyF+sf3dQlQgE=,iv:ShL914heYKA3pYDqMiO5S/o/p8ZfT7Rh2GS63ibhFZI=,tag:9xIUYWiNLmSvPNwP74OtqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
