apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-echo-headers-deployment
  labels:
    app.kubernetes.io/name: nginx-echo-headers
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-echo-headers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-echo-headers
        app.kubernetes.io/part-of: nginx-echo-headers
        app.kubernetes.io/component: omegaup-nginx-echo-headers
    spec:
      containers:
      - name: nginx-echo-headers
        image: brndnmtthws/nginx-echo-headers
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-echo-headers-service
  labels:
    app.kubernetes.io/name: nginx-echo-headers
spec:
  selector:
    app.kubernetes.io/name: nginx-echo-headers
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
